User_project/User_project/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('basic_app/',include('basic_app.urls')),
    path('logout/', views.user_logout,name='logout'),
    path('special/', views.special,name="special"),

]

User_project/basic_app/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

#template URLs
app_name='basic_app'

urlpatterns=[
    path('register/',views.register,name="register"),
    path('user_login/',views.user_login,name="user_login"),
]

User_project/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user=models.OneToOneField(User,on_delete=models.CASCADE)
    # In a one-to-one relationship,
    # one record in a table is associated with one and only one record in another table.
    # For example, in a school database, each student has only one student ID,
    # and each student ID is assigned to only one person.

    portfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

User_project/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model =UserProfileInfo
        fields=('portfolio_site','profile_pic')

User_project/basic_app/views.py
from django.shortcuts import render
from . import forms

#for login logout:-
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
#note: dont call a view to something which you import


# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

def register(request):

    registered=False

    if request.method == 'POST':
        user_form = forms.UserForm(request.POST)
        profile_form=forms.UserProfileInfoForm(request.POST)


        if user_form.is_valid() and profile_form.is_valid():

            user=user_form.save()
            user.set_password(user.password)
            #hashing the password
            user.save()
            #save the changes

            profile= profile_form.save(commit=False)
            profile.user = user
            #this sets up the one to one relationship

            #to check if there is in an image
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered= True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form= forms.UserForm()
        profile_form= forms.UserProfileInfoForm()

    return render(request,'basic_app/register.html',
    {"user_form":user_form,'profile_form':profile_form,'registered':registered})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))



@login_required
def special(request):
    logout(request)
    return HttpResponse("Congragulations! U have logged in !")



def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        #getting what the user has inputted via the name of the corresponding html tags

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                #redirecting to home page
                return HttpResponseRedirect(reverse('special'))

            else:
                return HttpResponse("Account not acitve")

        else:
            print("Someone tried to login and failed!")
            print("Username :{} and password {}".format(username,password))
            return HttpResponse('invalid login details!')

    else:
        return render(request,'basic_app/login.html',{})

User_project/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <style media="screen">

    </style>
    <nav class="navbar navbar-inverse ">
      <div class="conatiner">
        <ul class='nav navbar-nav'>
          <a href="{% url 'index' %}" class="navbar-brand">Home</a>
          <a class="navbar-brand" href="{%url 'basic_app:register' %}">Register</a>
          <a  class="navbar-brand" href="{%url 'admin:index'%}">Admin</a

            <!-- note: reative urls find views not files. It goes to the urls.py files and finds the views related to the app name. -->

            {%if user.is_authenticated %}

                 <ul class='nav navbar-nav navbar-right'>
                    <li><a class='navbar-brand 'href="{%url 'logout' %}">Logout</a></li>
                 </ul>

            {% else %}
                    <a class="navbar-brand nav navbar-nav navbar-right" href="{%url 'basic_app:user_login' %}">login</a>

            {% endif %}

        </ul>


      </div>
    </nav>
<div class="container">
  {%block body_block%}
  {%endblock%}
</div>


  </body>
</html>

User_project/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{%block body_block%}

<div class="jumbotron">
  <h1>Django Level Five!</h1>

</div>
{%endblock%}

User_project/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
<h1>Plz Login</h1>
<form action="{%url 'basic_app:user_login'%}" method="post">
  {%csrf_token%}
  <label for="username">Username:</label>
  <input type="text" name="username" placeholder="Enter Username">

  <label for="password">Password:</label>
  <input type="password" name='password' palceholder="Password">

  <input class="btn btn-primary "type="submit" name="" value="Login">

</form>
</div>

{%endblock%}

User_project/templates/basic_app/register.html
{%extends "basic_app/base.html"%}
{%load static%}

{%block body_block%}
<div class="jumbotron">
    {%if registered %}
        <h1>Thank You for registering!</h1>

    {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form:</h3>

    <form method="POST" enctype='maltipart/form-data'>
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Register">

    </form>
    {%endif%}
</div>
{%endblock%}